### ISSUE TITLE
implement storageManager API

### ISSUE THREAD

**Issue by ColdIV** [mc-cc-scripts/storageManager-prog#1]
To do so, add storageManager-lib and use it within the program.

The following functions should be implemented:
- getItems -> should return a list of all items with name, slots and amount
- push and pull items in between peripherals by name or slot with optional amount (defaults to 1)
(push always to controller, pull always from controller)
- search for substring return either single item or array of items if not unique (an item in this context is name, slot and amount)

_(names may vary)_

**Peripherals should be initialised within the library but are optional.**

**Push and Pull depend on Peripherals.**

**Comment by ChristophLHR** [comment]
- List peripherals
- Push / Pull accept a table as paramter
  - name : string
  - slot : number
  - amount: number | nil -- defaults to one
  - sourcePeripheral : string | nil -- defaults to "transferchest"
  - targetPeripheral : string | nil -- defaults to "controller"

**Comment by ColdIV** [comment]
@ChristophLHR the documentation should be done (I am currently testing the implementation)
Can you check if the documentation (within the README.md) is alright and matches the requirements? If so I will complete my tests and close this issue.

Since some changes were made to how it works, this issue does not properly reflect the structure of the commands.
push and pull do not take a table, since they now always need the peripherals anyway.

**Comment by ColdIV** [comment]
The base API is [now](https://github.com/mc-cc-scripts/storageManager-prog/commit/9202370796febdd05f6e4a037db3c9478bf8bcb5) implemented and should work.
